# -*- coding: utf-8 -*-
"""DataStandardization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dArSr7NUaOxBY0DNRfWAft2V3ZB86R0l

Data Sandardization :
 *   The process of standardizing the data to a common format and common range
"""

import  numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# loading the datasets
dataset = sklearn.datasets.load_breast_cancer()

print(dataset)

# loading the data fro a pandas data frame
df = pd.DataFrame(dataset.data,columns = dataset.feature_names)

df.head()

df.isnull().sum()

df.shape

X = df
Y = dataset.target

print(X)

print(Y)

"""Splitting the data into training data and test **data**"""

X_train,X_test,Y_train,Y_test = train_test_split(X, Y,test_size = 0.2,random_state=3)

print(X.shape,X_train.shape,X_test.shape)

"""Standardize the data"""

print(dataset.data.std())

scaler = StandardScaler()

scaler.fit(X_train)

X_train_Standardized = scaler.transform(X_train)

print(X_train_Standardized)

X_test_standrdized = scaler.transform(X_test)

print(X_train_Standardized.std())

print(X_test_standrdized.std())