# -*- coding: utf-8 -*-
"""HandalingImbalancedDataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JAQVE0caNof7QhsSZ_v_xW2p8kEynVjT

**Imbalanced Dataset :**

A dataset with unequal class disribution
"""

# importing the dependencies
import numpy as np
import pandas as pd

# loading the dataset to pandas DataFrame
credit_card_data = pd.read_csv('/content/credit_data.csv')

# first 5 rows of data frame
credit_card_data.head()

credit_card_data.tail()

# distribution of the two classes
credit_card_data['Class'].value_counts()

"""This is highly imbalanced Dataset

0 --> Legit Transactions

1 --> Fradulent Transections
"""

# sperating the legit and fradulent transactions
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

print(legit.shape)
print(fraud.shape)

"""Under-sampling

Build a sample dataset containing similar distribution of Legit & Fradulent Transactions

Number of Fradulent Transactions --> 492
"""

legit_sample = legit.sample(n=415)

print(legit_sample.shape)

"""Concatenate the Two DataFrames"""

new_dataset = pd.concat([legit_sample,fraud],axis = 0)

new_dataset.head()

new_dataset.tail()

new_dataset['Class'].value_counts()