# -*- coding: utf-8 -*-
"""Working with Matrix in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j4xDtWjj1M2upD9q_J2TDLHt9ExRSPLL
"""

import numpy as np

"""Creating a Matrix using numpy"""

matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

matrix_1.shape  # gives shape of matrix 2*2  - > row * column

matrix_2 = np.array([[45,65,78],[12,43,90],[34,76,21]])
print(matrix_2)

print(matrix_2.shape)

"""Creating Matrix with Random Values"""

random_matrix = np.random.rand(3,3)
print(random_matrix)

# Creating matrix with random integers
random_integer_matrix = np.random.randint(100, size = (4,5))
print(random_integer_matrix)

"""Matrix with all the values as 1"""

matrix_3 = np.ones((2,3))
print(matrix_3)

matrix_3 = np.ones((2,3),dtype = int)
print(matrix_3)

matrix_3 = np.ones((10,10),dtype = int)
print(matrix_3)

"""Null mMatrix or Zero matrix"""

null_matrix = np.zeros((4,4))
print(null_matrix)

null_matrix = np.zeros((7,7))
print(null_matrix)

"""Identity Matrix"""

identity_matrix = np.eye(3,3)
print(identity_matrix)

identity_matrix = np.eye(4,4)
print(identity_matrix)

"""Transpose of a Matrix"""

# Matrix with random integer values
a = np.random.randint(100,size=(4,5))
print(a)

transpose_of_a = np.transpose(a)
print(transpose_of_a)