# -*- coding: utf-8 -*-
"""HandalingMissingValues.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AVbDCssdYs4NW0F0Xzm0rvrPKtceP-y5

Methods to Handle Missing Values:


*   Imputation
*   Dropping

Importing te liraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# loading the dataset to a Panda Data frame
dataset = pd.read_csv('/content/Placement_Dataset.csv')
dataset.head()

dataset.shape

dataset.isnull().sum()

"""Central Tendencies:


1.   Mean
2.   Medium
3.   Mode





"""

# Analyse the distributation of data in the salary
fig,ax = plt.subplots(figsize=(6,6))
sns.distplot(dataset.salary)

"""Replace the missing values wtih Median value"""

dataset['salary'].fillna(dataset['salary'].median(),inplace = True)

# check number of missing value
dataset.isnull().sum()

# filling missing values with Mean value :
# dataset['salary'].fillna(dataset['salary'].mean(),inplace = True)

# filling missing values with Mode value :
# dataset['salary'].fillna(dataset['salary'].mode(),inplace = True)

"""Droping Method"""

salary_dataset = pd.read_csv('/content/Placement_Dataset.csv')

salary_dataset.shape

salary_dataset.isnull().sum()

# drope the missing values
salary_dataset = salary_dataset.dropna(how ='any')

salary_dataset.isnull().sum()

salary_dataset.shape