# -*- coding: utf-8 -*-
"""Seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JEfINGAI-NIdro2qkxzY41zTRpPaGiul

Seaboarn
*   Data Visualiation Library
"""

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

"""Note: Seaborn has some built-in datasets"""

# total bill vs tip dataset
tips = sns.load_dataset('tips')

tips.head()

# seting a theme for the plots
sns.set_theme()

# visualize the data
sns.relplot(data = tips, x = 'total_bill',y='tip',col='time',hue='smoker',style ='smoker',size = 'size')

# load the iris dataset
iris = sns.load_dataset('iris')
iris.head()

"""Scatter Plot"""

sns.scatterplot(x = 'sepal_length',y = 'petal_length',hue='species',data = iris )

sns.scatterplot(x = 'sepal_length',y = 'petal_width',hue='species',data = iris )

# loading the titanic datasets
titanic = sns.load_dataset('titanic')
titanic.head()

"""Count Plot"""

sns.countplot(x = 'class',data = titanic)

titanic.shape

sns.countplot(x= 'class', data = titanic)

sns.countplot(x= 'survived',data = titanic)

"""Bar Chart"""

sns.barplot(x = 'sex',y = 'survived',hue='class',data=titanic)

from sklearn.datasets import fetch_california_housing
house_dataset = fetch_california_housing()

house = pd.DataFrame(house_dataset.data,columns = house_dataset.feature_names)
house['PRICE'] = house_dataset.target

house.head()

print(house_dataset)

sns.displot(house["PRICE"])

"""Correlaton :

*   Positive Correlation
*   Negative Correlation

Heat Map
"""

correlation = house.corr()

# Constructing a Heat Map
plt.figure(figsize = (10,10))
sns.heatmap(correlation,cbar = True,square = True , fmt = '.1f',annot = True, annot_kws= {'size':8},cmap = 'Blues' )