# -*- coding: utf-8 -*-
"""VectorOperation-In-Python-Part2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s9dyqD7L9FNv2x6NBQ1KXbrXSvBYIvoJ
"""

import numpy as np

"""Dot Product of 2 Vectors"""

a = np.array([2,3])

b = np.array([4,4])

a_dot_b = np.dot(a,b)

print(a_dot_b)

c = np.array([40,20,35])

d = np.array([53,24,68])

c_dot_d = np.dot(c,d)

print(c_dot_d)

"""Cross Product of 2 Vectors"""

a = np.array([2, 3])

b = np.array([4, 4])

a_cross_b = np.cross(a,b)

print(a_cross_b)

c = np.array([5, 10, 20])

d = np.array([18, 32, 50])

c_cross_d = np.cross(c,d)

print(c_cross_d)

"""Projection of 'a' vector on 'v' vector

The projection of
→
A
 on
→
V
 is defined as
→
A
.
→
V
|
→
V
|
=
→
A
.
^
V


"""

a = np.array([2,3])

v = np.array([8,6])

# magnitude of "v" vector
magnitude_of_v = np.sqrt(sum(v**2))

proj_of_a_on_v = (np.dot(a,v)/magnitude_of_v**2)*v

print('Projection of a vector on v vector =',proj_of_a_on_v)

a = np.array([2,3,8])

v = np.array([8,6,2])

# magnitude of "v" vector
magnitude_of_v = np.sqrt(sum(v**2))

proj_of_a_on_v = (np.dot(a,v)/magnitude_of_v**2)*v

print('Projection of a vector on v vector =',proj_of_a_on_v)